backend:
  #name: test-repo
  name: git-gateway
  branch: master

media_folder: /static/img
public_folder: /img

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/pages/portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portfolio-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Kategorie", name: "category", widget: "select", options: ["web", "bild", "film"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Titelbild", name: image, widget: image}
      - {label: "Beschreibung", name: "description", widget: "text"}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Service", name: service, widget: list, fields: [
          {label: name, name: "name", widget: string}
        ]}
      - {label: "Icons", name: icons, widget: list, fields: [
          {label: Icon, name: "icon", widget: image}
        ]}
      - {label: "Gallery", name: gallery, widget: list, fields: [
          {label: Bild, name: "image", widget: image}
        ]}
  - name: "pages"
    label: "Seiten"
    files:
      - file: "src/pages/team/team.md"
        label: "Team"
        name: "team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/team/"}
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Titelbild", name: image, widget: image}
          - {label: "Text", name: "body", widget: "markdown"}
          - {label: Mitarbeiter, name: mitarbeiter, widget: list, fields: [
              {label: Name, name: "name", widget: string},
              {label: Bild, name: bild, widget: image, required: false},
              {label: E-Mail, name: mail, widget: string},
              {label: Funktion, name: text, widget: string},
            ]}

      - file: "src/pages/index/index.md"
        label: "Startseite"
        name: "index"
        delete: false
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Titelbild", name: image, widget: "image"}
          - label: "Slogan"
            name: slogan
            widget: "object"
            fields:
              - {label: "Titel", name: title, widget: string}
              - {label: "Text", name: text, widget: text}

          - label: "Features"
            name: features
            widget: "list"
            fields:
              - {label: "Titel", name: title , widget: string}
              - {label: "Bild", name: image , widget: image}
              - {label: "Text", name: text , widget: text}
          - {label: "Mockup-Bild", name: "mockupimage" , widget: image}
          - {label: "Profil", name: box, widget: object, fields: [
              {label: "Titel", name: "title", widget: "string"},
              {label: "Text", name: "text", widget: "markdown"},
             ]}
          - {label: "Portfolio", name: portfolios, widget: list, fields: [
              {label: "Titel", name: "title", widget: "string"},
              {label: "URL", name: "url", widget: "relation", collection: "portfolio", searchFields: [title, description, path], valueField: path},
              {label: "Bild", name: "image" , widget: image},
             ]}
          - {label: "Kunden", name: kunden, widget: object, fields: [
              {label: "Titel", name: "title", widget: "string"},
              {label: "Kunde", name: kunde, widget: list, fields: [
                  {label: "Name", name: "name", widget: "string"},
                  {label: "Bild", name: "image", widget: "image"},
                  {label: "Link", name: "url", widget: "string"},
                ]}
              ]}
          - {label: "Kontakt", name: kontakt, widget: object, fields: [
              {label: "Titel", name: "title", widget: "string"},
              {label: "Text", name: "text", widget: "text"},
              {label: "Bild", name: "image", widget: "image"},
              {label: "URL", name: "path", widget: "string"},
              {label: "Button Text", name: "buttontext", widget: "string"},
            ]}

      - file: "src/pages/kontakt/kontakt.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "kontakt-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/kontakt/"}
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Titelbild", name: image, widget: image, required: false}
          - {label: "Text", name: "body", widget: "markdown"}

      - file: "src/pages/impressum.md"
        label: "Impressum"
        name: "impressum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "artikel-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/impressum/"}
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Titelbild", name: image, widget: image, required: false}
          - {label: "Text", name: "body", widget: "markdown"}

      - file: "src/pages/404.md"
        label: "404"
        name: "404"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "artikel-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/404.html"}
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Titelbild", name: image, widget: image, required: false}
          - {label: "Text", name: "body", widget: "markdown"}
