backend:
  #name: test-repo
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/pages/portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portfolio-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Seiten"
    files:
      - file: "src/pages/team/team.md"
        label: "Team"
        name: "team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/team/"}
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Titelbild", name: image, widget: image, required: false}
          - {label: "Beschreibung des Unternehmens", name: "body", widget: "markdown"}
          - {label: Mitarbeiter, name: mitarbeiter, widget: list, fields: [
              {label: Name, name: "name", widget: string},
              {label: Bild, name: bild, widget: image, required: false},
              {label: E-Mail, name: mail, widget: string},
              {label: Beschreibung, name: beschreibung, widget: text},
            ]}

      - file: "src/pages/index/index.md"
        label: "Startseite"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Titelbild", name: image, widget: image, required: false}
          - {label: "Slogan", name: slogans, widget: list, fields: [
              {label: "Slogane-Text", name: "slogan", widget: "string"},
             ]}
          - {label: "Kunden", name: kunden, widget: list, fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Bild", name: "bild", widget: "image"},
              {label: "Link", name: "url", widget: "string"},
          ]}


      - file: "src/pages/product/product.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/products"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
